spring.application.name=ultimate-hotel-software-v3.0

spring.datasource.url=jdbc:mysql://localhost:3306/jwt_practice_db?createDatabaseIfNotExist=true&serverTimezone=UTC

spring.datasource.username=root

spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971

# 604800000 ms equivale exactamente a 7 días (ideal para el Refresh Token)
refresh.expiration=604800000

# 180000 ms equivale exactamente a 3 min (ideal para el access Token)
access.expiration=180000

